### ISSUE TITLE
climits.h: No such file or directory

### ISSUE THREAD

**Issue by MarkusPL0** [wladimir-computin/CC1101-ESP-Arduino#9]
when I try to compile your code (CC1101_ESP library) I get the error:

**climits.h: No such file or directory**

I tried to compile it under Arduino IDE 1.8.x under Ubuntu and freshly installed Arduino IDE 2.2.x under Windows 10

Could I ask for some advice?

Markus

**Comment by arankyr** [comment]
having same issue :(

**Comment by wischbgr** [comment]
Hey there, can you please try to comment out the following line in `CC1101_ESP_Arduino.h`:

`#include <climits.h>`

and try again?

**Comment by MarkusPL0** [comment]
Hi,

after commenting out #include <climits.h>  I got following error (see below). However after changing 

#include <climits.h>  to #include <limits.h>  it compiles on Windows and Arduino IDE 2.2  (and ESP8266 board selected)
-----------------------------------------------------------
C:\Users\user1\AppData\Local\Arduino15\libraries\CC1101-ESP-Arduino\CC1101_ESP_Arduino.cpp: In member function 'void CC1101::setDeviationHZ(int)':
C:\Users\user1\AppData\Local\Arduino15\libraries\CC1101-ESP-Arduino\CC1101_ESP_Arduino.cpp:267:16: error: 'INT_MAX' was not declared in this scope
  267 |  int closest = INT_MAX;
      |                ^~~~~~~
C:\Users\user1\AppData\Local\Arduino15\libraries\CC1101-ESP-Arduino\CC1101_ESP_Arduino.cpp:18:1: note: 'INT_MAX' is defined in header '<climits>'; did you forget to '#include <climits>'?
   17 | #include "CC1101_ESP_Arduino.h"
  +++ |+#include <climits>
   18 | 
-------------------------------------------------------------------------------------------------

BTW did you test your library or ESP8266?

**Comment by arankyr** [comment]
> Hi,
> 
> after commenting out #include <climits.h> I got following error (see below). However after changing
> 
> ## #include <climits.h> to #include <limits.h> it compiles on Windows and Arduino IDE 2.2 (and ESP8266 board selected)
> ## C:\Users\user1\AppData\Local\Arduino15\libraries\CC1101-ESP-Arduino\CC1101_ESP_Arduino.cpp: In member function 'void CC1101::setDeviationHZ(int)':
> C:\Users\user1\AppData\Local\Arduino15\libraries\CC1101-ESP-Arduino\CC1101_ESP_Arduino.cpp:267:16: error: 'INT_MAX' was not declared in this scope
> 267 | int closest = INT_MAX;
> | ^~~~~~~
> C:\Users\user1\AppData\Local\Arduino15\libraries\CC1101-ESP-Arduino\CC1101_ESP_Arduino.cpp:18:1: note: 'INT_MAX' is defined in header ''; did you forget to '#include '?
> 17 | #include "CC1101_ESP_Arduino.h"
> +++ |+#include
> 18 |
> BTW did you test your library or ESP8266?

i got this working by downloading a previous version of it:
https://github.com/wladimir-computin/CC1101-ESP-Arduino/tree/8c9c9edb33650d770d8466fea44b97480f84ed2a
